-- Vollständiger Boden-Katalog für neue und bestehende Betriebe.
-- Persönlich geänderte Preise bleiben unangetastet; ergänzt werden nur fehlende
-- Kombinationen aus Bezeichnung und Einheit.

insert into price_items (company_id, category, title, unit, unit_price)
select c.id, p.category, p.title, p.unit, p.unit_price
from companies c
cross join (values
  ('Boden – Anfahrt & Organisation', 'Anfahrt pauschal (bis 20 km)', 'Pauschale', 45.00::numeric),
  ('Boden – Anfahrt & Organisation', 'Anfahrt je Kilometer (ab 20 km)', 'km', 0.50::numeric),
  ('Boden – Anfahrt & Organisation', 'Parkgebühren / Halteverbotszone', 'Pauschale', 30.00::numeric),
  ('Boden – Anfahrt & Organisation', 'Materialtransport zur Baustelle', 'Pauschale', 40.00::numeric),
  ('Boden – Anfahrt & Organisation', 'Entsorgungsfahrt (Altbelag, Verpackung)', 'Fahrt', 60.00::numeric),
  ('Boden – Anfahrt & Organisation', 'Besichtigungstermin / Aufmaß vor Ort', 'Stunde', 65.00::numeric),
  ('Boden – Vorbereitung & Schutz', 'Möbel rücken / ausräumen', 'Stunde', 55.00::numeric),
  ('Boden – Vorbereitung & Schutz', 'Möbel zurückrücken', 'Stunde', 55.00::numeric),
  ('Boden – Vorbereitung & Schutz', 'Türen unterkürzen (Aufkantung Belag)', 'Stück', 25.00::numeric),
  ('Boden – Vorbereitung & Schutz', 'Untergrundprüfung (Ebenheit, Feuchte, Tragfähigkeit)', 'Pauschale', 45.00::numeric),
  ('Boden – Altbelag entfernen', 'Teppichboden entfernen und entsorgen', 'm²', 6.00::numeric),
  ('Boden – Altbelag entfernen', 'Laminat demontieren und entsorgen', 'm²', 5.00::numeric),
  ('Boden – Altbelag entfernen', 'Vinyl / PVC entfernen und entsorgen', 'm²', 7.00::numeric),
  ('Boden – Altbelag entfernen', 'Linoleum entfernen und entsorgen', 'm²', 8.00::numeric),
  ('Boden – Altbelag entfernen', 'Parkett demontieren (schwimmend)', 'm²', 7.00::numeric),
  ('Boden – Altbelag entfernen', 'Parkett demontieren (verklebt, aufwändig)', 'm²', 18.00::numeric),
  ('Boden – Altbelag entfernen', 'Klebstoffreste / Altkleber abfräsen', 'm²', 14.00::numeric),
  ('Boden – Altbelag entfernen', 'Sockelleisten entfernen (alt)', 'lfdm', 2.00::numeric),
  ('Boden – Altbelag entfernen', 'Schwelle / Übergangsprofil entfernen', 'Stück', 8.00::numeric),
  ('Boden – Altbelag entfernen', 'Bauschutt / Altbelag entsorgen (Sackweise)', 'Sack', 12.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrund kehren / saugen (Vorbereitung)', 'm²', 1.50::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrund grundieren (Haftgrund / Tiefengrund)', 'm²', 5.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrund spachteln / ausgleichen (bis 5mm)', 'm²', 12.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrund spachteln / ausgleichen (bis 20mm)', 'm²', 20.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrund schleifen (Unebenheiten, Kleberreste)', 'm²', 7.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Risse im Estrich vorbehandeln (Kleber / Gewebe)', 'lfdm', 8.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Trittschalldämmung verlegen (PE-Schaum / Filz)', 'm²', 4.50::numeric),
  ('Boden – Untergrundvorbereitung', 'Dampfbremse / PE-Folie verlegen (Feuchtigkeitsschutz)', 'm²', 3.50::numeric),
  ('Boden – Untergrundvorbereitung', 'Feuchtemessung Estrich (CM-Messung)', 'Messung', 35.00::numeric),
  ('Boden – Parkett', 'Fertigparkett verlegen schwimmend (Klick-System)', 'm²', 22.00::numeric),
  ('Boden – Parkett', 'Fertigparkett verlegen vollflächig verklebt', 'm²', 35.00::numeric),
  ('Boden – Parkett', 'Mehrschichtparkett verlegen schwimmend', 'm²', 28.00::numeric),
  ('Boden – Parkett', 'Mehrschichtparkett verlegen vollflächig verklebt', 'm²', 42.00::numeric),
  ('Boden – Parkett', 'Massivparkett (Stabparkett) verlegen vollflächig verklebt', 'm²', 55.00::numeric),
  ('Boden – Parkett', 'Landhausdiele verlegen schwimmend (Klick)', 'm²', 25.00::numeric),
  ('Boden – Parkett', 'Landhausdiele verlegen vollflächig verklebt', 'm²', 40.00::numeric),
  ('Boden – Parkett', 'Mosaikparkett / Industrieparkett verlegen (verklebt)', 'm²', 50.00::numeric),
  ('Boden – Parkett', 'Aufpreis Fischgrät-Verlegemuster', 'm²', 14.00::numeric),
  ('Boden – Parkett', 'Aufpreis Schachbrett-Muster / Kassetten', 'm²', 18.00::numeric),
  ('Boden – Parkett', 'Aufpreis Diagonalverlegung', 'm²', 10.00::numeric),
  ('Boden – Parkett', 'Aufpreis Verlegung bei Fußbodenheizung (elastischer Kleber)', 'm²', 8.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett abschleifen (maschinell, 1 Schleifgang)', 'm²', 12.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett abschleifen (maschinell, 2 Schleifgänge inkl. Rand)', 'm²', 20.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett abschleifen komplett (stark beschädigt, 3 Schleifgänge)', 'm²', 30.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett versiegeln (Lack, 2-lagig)', 'm²', 18.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett ölen (maschinell, 1-lagig)', 'm²', 20.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett ölen (maschinell, 2-lagig inkl. Einarbeiten)', 'm²', 28.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett wachsen', 'm²', 14.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett beizen (Färben vor Versiegelung)', 'm²', 12.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Fugen kitten / Risse ausspachteln', 'm²', 8.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Einzelstäbe / beschädigte Felder austauschen', 'Stück', 35.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett schleifen + versiegeln komplett (2x schleifen, 2x Lack)', 'm²', 38.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett schleifen + ölen komplett (2x schleifen, 2x Öl)', 'm²', 45.00::numeric),
  ('Boden – Laminat', 'Laminat verlegen schwimmend (Klick-System, Standard)', 'm²', 14.00::numeric),
  ('Boden – Laminat', 'Laminat verlegen schwimmend (Großdiele / breites Format)', 'm²', 16.00::numeric),
  ('Boden – Laminat', 'Aufpreis Diagonalverlegung Laminat', 'm²', 8.00::numeric),
  ('Boden – Laminat', 'Aufpreis Fischgrät / Muster Laminat', 'm²', 12.00::numeric),
  ('Boden – Laminat', 'Aufpreis Verlegung bei Fußbodenheizung (FBH-geeignet)', 'm²', 4.00::numeric),
  ('Boden – Vinyl / LVT', 'Klick-Vinyl (LVT) verlegen schwimmend, Standard', 'm²', 16.00::numeric),
  ('Boden – Vinyl / LVT', 'Klick-Vinyl (SPC) verlegen schwimmend (Vollkern, wasserfest)', 'm²', 18.00::numeric),
  ('Boden – Vinyl / LVT', 'Klebe-Vinyl verlegen vollflächig (Dünnbett, Self-Adhesive)', 'm²', 22.00::numeric),
  ('Boden – Vinyl / LVT', 'Klebe-Vinyl verlegen vollflächig (Profikleber, Nasskleber)', 'm²', 28.00::numeric),
  ('Boden – Vinyl / LVT', 'Vinyl-Planken verlegen (Einzelplanken, Klick)', 'm²', 17.00::numeric),
  ('Boden – Vinyl / LVT', 'Vinyl-Fliesen verlegen (Klick oder Klebe)', 'm²', 20.00::numeric),
  ('Boden – Vinyl / LVT', 'WPC-Boden / Outdoorvinyl verlegen (Terrasse / Feuchtraum)', 'm²', 25.00::numeric),
  ('Boden – Vinyl / LVT', 'Aufpreis Diagonalverlegung Vinyl', 'm²', 8.00::numeric),
  ('Boden – Vinyl / LVT', 'Aufpreis Fußbodenheizung Vinyl', 'm²', 4.00::numeric),
  ('Boden – PVC / Elastisch', 'PVC-Belag verlegen vollflächig verklebt (Rollenware)', 'm²', 18.00::numeric),
  ('Boden – PVC / Elastisch', 'PVC-Belag verlegen lose / locker verlegt', 'm²', 12.00::numeric),
  ('Boden – PVC / Elastisch', 'CV-Belag (Cushion Vinyl) verlegen vollflächig', 'm²', 20.00::numeric),
  ('Boden – PVC / Elastisch', 'Gummibelag verlegen (Gewerbe, Küche, Keller)', 'm²', 28.00::numeric),
  ('Boden – PVC / Elastisch', 'Antistatischer / ESD-Boden verlegen (EDV, Reinraum)', 'm²', 38.00::numeric),
  ('Boden – PVC / Elastisch', 'Industrieboden / Gewerbeboden verlegen (strapazierfähig)', 'm²', 32.00::numeric),
  ('Boden – Linoleum', 'Linoleum verlegen vollflächig verklebt (Rollenware)', 'm²', 22.00::numeric),
  ('Boden – Linoleum', 'Linoleum verlegen (Fliesen-/Plattenformat)', 'm²', 26.00::numeric),
  ('Boden – Linoleum', 'Linoleum verschweißen (Hohlkehlsockel, Nahtschweißung)', 'lfdm', 10.00::numeric),
  ('Boden – Linoleum', 'Linoleum Hohlkehle / Sockelaufkantung ziehen', 'lfdm', 14.00::numeric),
  ('Boden – Teppichboden', 'Teppichboden verlegen (gespannt / Tackern auf Nagelleiste)', 'm²', 14.00::numeric),
  ('Boden – Teppichboden', 'Teppichboden verlegen vollflächig verklebt', 'm²', 18.00::numeric),
  ('Boden – Teppichboden', 'Teppichboden verlegen lose (doppelseitiges Klebeband)', 'm²', 10.00::numeric),
  ('Boden – Teppichboden', 'Teppichfliesen verlegen (selbsthaftend)', 'm²', 12.00::numeric),
  ('Boden – Teppichboden', 'Teppich vernähen / Naht verkleben', 'lfdm', 8.00::numeric),
  ('Boden – Teppichboden', 'Nagelleiste / Gripliste setzen', 'lfdm', 4.00::numeric),
  ('Boden – Kork', 'Korkboden verlegen schwimmend (Klick-System)', 'm²', 18.00::numeric),
  ('Boden – Kork', 'Korkboden verlegen vollflächig verklebt', 'm²', 24.00::numeric),
  ('Boden – Kork', 'Korkboden schleifen und versiegeln', 'm²', 22.00::numeric),
  ('Boden – Trockenestrich', 'Trockenestrich (GK-Elemente) auf Schüttung verlegen', 'm²', 48.00::numeric),
  ('Boden – Trockenestrich', 'Trockenestrich auf Trittschall (ohne Schüttung)', 'm²', 38.00::numeric),
  ('Boden – Trockenestrich', 'Schüttung einbringen und abziehen (Blähton)', 'm²', 22.00::numeric),
  ('Boden – Abschlussarbeiten', 'Sockelleisten montieren (Holz / MDF / Kunststoff)', 'lfdm', 5.50::numeric),
  ('Boden – Abschlussarbeiten', 'Sockelleisten lackieren / streichen (nach Montage)', 'lfdm', 3.50::numeric),
  ('Boden – Abschlussarbeiten', 'Übergangsprofil / Schwelle einbauen', 'Stück', 15.00::numeric),
  ('Boden – Abschlussarbeiten', 'T-Profil / Reduzierprofil zwischen Belägen', 'Stück', 12.00::numeric),
  ('Boden – Abschlussarbeiten', 'Wandanschlussprofil / Abschlussprofil setzen', 'lfdm', 6.00::numeric),
  ('Boden – Abschlussarbeiten', 'Treppennase / Kantenprofil Treppe montieren', 'Stück', 22.00::numeric),
  ('Boden – Abschlussarbeiten', 'Treppenstufe mit Belag belegen (schwimmend / geklebt)', 'Stück', 45.00::numeric),
  ('Boden – Abschlussarbeiten', 'Silikonfuge setzen (Wandanschluss)', 'lfdm', 6.00::numeric),
  ('Boden – Abschlussarbeiten', 'Heizungsrohr-Abdeckrosette einbauen', 'Stück', 8.00::numeric),
  ('Boden – Abschlussarbeiten', 'Türzarge unterkürzen für neuen Belagsaufbau', 'Stück', 25.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag Kleinfläche (<10 m² Gesamtfläche)', 'Pauschale', 80.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag viele kleine Räume / Durchgänge', 'Pauschale', 60.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag bewohnte Wohnung / eingeschränkter Zugang', 'Pauschale', 80.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag sehr schlechter Untergrund (aufwändige Vorbereitung)', 'm²', 8.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag Fußbodenheizung (CM-Messung, erhöhte Sorgfalt)', 'Pauschale', 55.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag Treppenstufen (aufwändig, viele Zuschnitte)', 'Pauschale', 80.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Zuschlag Wochenend- / Feiertagsarbeit (25%)', 'Pauschale', 25.00::numeric),
  ('Boden – Reinigung & Entsorgung', 'Baustelle kehren / saugen nach Verlegung', 'Pauschale', 35.00::numeric),
  ('Boden – Reinigung & Entsorgung', 'Neuen Boden reinigen / Schutzfolie entfernen', 'm²', 1.50::numeric),
  ('Boden – Reinigung & Entsorgung', 'Verpackungen / Kartonagen entsorgen', 'Pauschale', 20.00::numeric),
  ('Boden – Reinigung & Entsorgung', 'Altbelag entsorgen (Sackweise)', 'Sack', 12.00::numeric),
  ('Boden – Stundenleistungen', 'Regiearbeit Geselle Bodenleger', 'Stunde', 58.00::numeric),
  ('Boden – Stundenleistungen', 'Regiearbeit Parkettleger / Meister', 'Stunde', 75.00::numeric),
  ('Boden – Stundenleistungen', 'Kleinstauftrag pauschal (Mindestbetrag)', 'Pauschale', 110.00::numeric),
  ('Boden – Altbelag entfernen', 'Teppichboden verklebt entfernen', 'm²', 9.00::numeric),
  ('Boden – Altbelag entfernen', 'Teppichfliesen entfernen', 'm²', 6.50::numeric),
  ('Boden – Altbelag entfernen', 'Klick-Vinyl demontieren und entsorgen', 'm²', 5.50::numeric),
  ('Boden – Altbelag entfernen', 'Klebe-Vinyl / Designbelag entfernen', 'm²', 12.00::numeric),
  ('Boden – Altbelag entfernen', 'PVC- / CV-Belag verklebt entfernen', 'm²', 10.00::numeric),
  ('Boden – Altbelag entfernen', 'Korkboden entfernen und entsorgen', 'm²', 9.00::numeric),
  ('Boden – Altbelag entfernen', 'Gummi- / Kautschukbelag entfernen', 'm²', 14.00::numeric),
  ('Boden – Altbelag entfernen', 'OSB- / Spanplattenboden demontieren', 'm²', 12.00::numeric),
  ('Boden – Altbelag entfernen', 'Trockenestrich rückbauen', 'm²', 18.00::numeric),
  ('Boden – Altbelag entfernen', 'Nagelleisten / Gripper entfernen', 'lfdm', 2.50::numeric),
  ('Boden – Untergrundvorbereitung', 'Altkleber abschaben', 'm²', 8.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrund fräsen / kugelstrahlen', 'm²', 16.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Estrich anschleifen und absaugen', 'm²', 8.50::numeric),
  ('Boden – Untergrundvorbereitung', 'Schnellgrundierung auf nicht saugendem Untergrund', 'm²', 6.50::numeric),
  ('Boden – Untergrundvorbereitung', 'Ausgleichsmasse bis 3 mm einbringen', 'm²', 10.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Ausgleichsmasse 3–10 mm einbringen', 'm²', 16.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Ausgleichsmasse 10–30 mm einbringen', 'm²', 26.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Standfeste Spachtelung für Gefälle und Randbereiche', 'm²', 22.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Estrichriss kraftschlüssig verharzen und verklammern', 'lfdm', 18.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Epoxidharz-Feuchtigkeitssperre zweilagig', 'm²', 24.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Entkopplungsmatte verlegen', 'm²', 9.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Holzdielen verschrauben / nachbefestigen', 'm²', 10.00::numeric),
  ('Boden – Untergrundvorbereitung', 'OSB-Verlegeplatten auf Untergrund montieren', 'm²', 22.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Höhenausgleich mit Holzwerkstoffplatten', 'm²', 26.00::numeric),
  ('Boden – Parkett', 'Massivholzdielen verlegen verschraubt', 'm²', 48.00::numeric),
  ('Boden – Parkett', 'Massivholzdielen verlegen vollflächig verklebt', 'm²', 52.00::numeric),
  ('Boden – Parkett', 'Stabparkett im englischen Verband verlegen', 'm²', 58.00::numeric),
  ('Boden – Parkett', 'Stabparkett im Fischgrätmuster verlegen', 'm²', 68.00::numeric),
  ('Boden – Parkett', 'Stabparkett im französischen Fischgrät verlegen', 'm²', 78.00::numeric),
  ('Boden – Parkett', 'Hochkantlamellenparkett / Industrieparkett verlegen', 'm²', 52.00::numeric),
  ('Boden – Parkett', 'Bambusparkett verlegen vollflächig verklebt', 'm²', 42.00::numeric),
  ('Boden – Laminat', 'Feuchtraumlaminat verlegen schwimmend', 'm²', 18.00::numeric),
  ('Boden – Laminat', 'Laminat im Fischgrätmuster verlegen', 'm²', 24.00::numeric),
  ('Boden – Laminat', 'Laminat auf Treppenstufen verlegen', 'Stück', 48.00::numeric),
  ('Boden – Vinyl / LVT', 'Loose-Lay-Vinyl verlegen', 'm²', 18.00::numeric),
  ('Boden – Vinyl / LVT', 'Dryback-Designbelag vollflächig kleben', 'm²', 28.00::numeric),
  ('Boden – Vinyl / LVT', 'Designbelag im Fischgrätmuster kleben', 'm²', 36.00::numeric),
  ('Boden – Vinyl / LVT', 'Designbelag mit Fries / Bordüre verlegen', 'm²', 42.00::numeric),
  ('Boden – Vinyl / LVT', 'Vinyl auf Treppenstufen kleben', 'Stück', 55.00::numeric),
  ('Boden – PVC / Elastisch', 'PVC- / CV-Belag Nähte kaltverschweißen', 'lfdm', 7.00::numeric),
  ('Boden – PVC / Elastisch', 'Kautschukbelag vollflächig verkleben', 'm²', 32.00::numeric),
  ('Boden – PVC / Elastisch', 'Leitfähigen ESD-Boden mit Kupferband verlegen', 'm²', 48.00::numeric),
  ('Boden – Linoleum', 'Linoleum Intarsien / Muster schneiden und verlegen', 'm²', 42.00::numeric),
  ('Boden – Linoleum', 'Linoleum auf Treppenstufen verlegen', 'Stück', 58.00::numeric),
  ('Boden – Teppichboden', 'Nadelvlies vollflächig verkleben', 'm²', 16.00::numeric),
  ('Boden – Teppichboden', 'Sisal- / Kokosbelag vollflächig verkleben', 'm²', 24.00::numeric),
  ('Boden – Teppichboden', 'Teppichunterlage / Dämmunterlage verlegen', 'm²', 6.00::numeric),
  ('Boden – Teppichboden', 'Teppich auf Treppenstufen verlegen', 'Stück', 48.00::numeric),
  ('Boden – Kork', 'Korkboden ölen / wachsen', 'm²', 14.00::numeric),
  ('Boden – Abschlussarbeiten', 'Massivholz-Sockelleisten montieren', 'lfdm', 8.00::numeric),
  ('Boden – Abschlussarbeiten', 'Hamburger / Berliner Sockelleisten montieren', 'lfdm', 11.00::numeric),
  ('Boden – Abschlussarbeiten', 'Sockelleisten auf Gehrung schneiden (Außen-/Innenecke)', 'Stück', 6.00::numeric),
  ('Boden – Abschlussarbeiten', 'Kabelkanal-Sockelleisten montieren', 'lfdm', 9.00::numeric),
  ('Boden – Abschlussarbeiten', 'Weichsockelleisten / Kernsockelleisten kleben', 'lfdm', 7.00::numeric),
  ('Boden – Abschlussarbeiten', 'Hohlkehlsockel aus Bodenbelag herstellen', 'lfdm', 16.00::numeric),
  ('Boden – Abschlussarbeiten', 'Dehnungsfuge mit Bewegungsprofil herstellen', 'lfdm', 18.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Lose Parkettstäbe nachkleben', 'Stück', 22.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Kleine Parkettschäden ausbessern / Hartwachsreparatur', 'Stück', 28.00::numeric),
  ('Boden – Parkett Aufarbeitung', 'Parkett partiell nachschleifen und nachölen', 'm²', 32.00::numeric),
  ('Boden – Abschlussarbeiten', 'Bodentank / Revisionsdeckel passgenau ausschneiden', 'Stück', 35.00::numeric),
  ('Boden – Untergrundvorbereitung', 'Untergrundvorbereitung / Ausgleich', 'm²', 12.00::numeric),
  ('Boden – Feuchtigkeitsschutz', 'Epoxidharz-Feuchtigkeitssperre aufwalzen', 'm²', 18.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Erschwerniszuschlag Verlegung auf vorhandenen Belag', '%', 10.00::numeric),
  ('Boden – Erschwernisse & Zuschläge', 'Erschwerniszuschlag Muster-/Intarsienverlegung', '%', 30.00::numeric)
) as p(category, title, unit, unit_price)
where (
    'boden_parkett' = any(coalesce(c.gewerke, '{}'::text[]))
    or exists (
      select 1 from price_items existing_trade
      where existing_trade.company_id = c.id
        and existing_trade.category like 'Boden %'
    )
  )
  and not exists (
    select 1
    from price_items existing
    where existing.company_id = c.id
      and lower(existing.title) = lower(p.title)
      and lower(existing.unit) = lower(p.unit)
  );
