-- Vollständiger Maler- und Lackiererkatalog für neue und bestehende Betriebe.
-- Persönlich geänderte Preise bleiben unangetastet; ergänzt werden nur fehlende
-- Kombinationen aus Bezeichnung und Einheit.

update price_items
set category = 'Maler – Tapezieren'
where category = 'Maler – Tapezierarbeiten'
  and lower(title) = lower('Akzentwand Vliestapete');

insert into price_items (company_id, category, title, unit, unit_price)
select c.id, p.category, p.title, p.unit, p.unit_price
from companies c
cross join (values
  ('Maler – Anfahrt & Organisation', 'Anfahrt pauschal (bis 20 km)', 'Pauschale', 45.00::numeric),
  ('Maler – Anfahrt & Organisation', 'Anfahrt je Kilometer (ab 20 km)', 'km', 0.50::numeric),
  ('Maler – Anfahrt & Organisation', 'Parkgebühren / Halteverbotszone', 'Pauschale', 30.00::numeric),
  ('Maler – Anfahrt & Organisation', 'Materialtransport zur Baustelle', 'Pauschale', 35.00::numeric),
  ('Maler – Anfahrt & Organisation', 'Entsorgungsfahrt (Farbreste, Müll)', 'Fahrt', 60.00::numeric),
  ('Maler – Anfahrt & Organisation', 'Besichtigungstermin / Aufmaß vor Ort', 'Stunde', 65.00::numeric),
  ('Maler – Vorbereitung & Schutz', 'Möbel rücken / ausräumen', 'Stunde', 55.00::numeric),
  ('Maler – Vorbereitung & Schutz', 'Möbel abdecken mit Folie', 'm²', 1.50::numeric),
  ('Maler – Vorbereitung & Schutz', 'Boden abdecken (Abdeckvlies)', 'm²', 1.20::numeric),
  ('Maler – Vorbereitung & Schutz', 'Abkleben Kanten / Leisten', 'lfdm', 0.80::numeric),
  ('Maler – Vorbereitung & Schutz', 'Abkleben Fenster-/Türrahmen', 'Stück', 8.00::numeric),
  ('Maler – Vorbereitung & Schutz', 'Abkleben Schalter / Steckdosen', 'Stück', 3.00::numeric),
  ('Maler – Vorbereitung & Schutz', 'Schutzfolie Glas / Fenster', 'm²', 2.00::numeric),
  ('Maler – Vorbereitung & Schutz', 'Treppenschutz anbringen', 'lfdm', 3.50::numeric),
  ('Maler – Vorbereitung & Schutz', 'Tür aushängen und wieder einhängen', 'Stück', 25.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Untergrund prüfen und dokumentieren', 'Pauschale', 40.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Alten Anstrich abwaschen', 'm²', 3.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Tapete ablösen (einlagig)', 'm²', 4.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Tapete ablösen (mehrlagig, Aufpreis)', 'm²', 2.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Tapete ablösen mit Dampfgerät', 'm²', 5.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Kleisterreste entfernen', 'm²', 2.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Schimmel behandeln (Schimmelschutzgrund)', 'm²', 12.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Risse / Löcher spachteln (klein)', 'Stück', 8.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Fläche spachteln (Flächenspachtel)', 'm²', 9.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Schleifen von Hand', 'm²', 4.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Schleifen maschinell (Langhalsschleifer)', 'm²', 5.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Grundieren (Tiefengrund)', 'm²', 4.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Grundieren (Haftgrund / Sperrgrund)', 'm²', 6.00::numeric),
  ('Maler – Untergrundvorbereitung', 'GK-Fugen verspachteln inkl. Gewebe', 'lfdm', 5.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Putz ausbessern', 'm²', 18.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Dübellöcher spachteln', 'Stück', 3.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Untergrund entstauben / absaugen', 'm²', 1.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Leimfarbenanstrich abwaschen', 'm²', 6.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Kalkfarbenanstrich abbürsten', 'm²', 5.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Dispersionsanstrich anschleifen', 'm²', 3.50::numeric),
  ('Maler – Untergrundvorbereitung', 'Lackanstrich anschleifen', 'm²', 7.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Spachtelung Q1', 'm²', 6.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Spachtelung Q2', 'm²', 9.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Spachtelung Q3', 'm²', 14.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Spachtelung Q4', 'm²', 22.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Eckschutzschiene setzen und verspachteln', 'lfdm', 8.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Armierungsgewebe vollflächig einbetten', 'm²', 13.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Isoliergrund gegen Nikotin / Ruß / Wasserflecken', 'm²', 9.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Tapetenwechselgrund auftragen', 'm²', 5.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Makulatur / Renoviervlies als Untergrund kleben', 'm²', 12.00::numeric),
  ('Maler – Anstrich Innen', 'Decke streichen 1x Anstrich', 'm²', 7.00::numeric),
  ('Maler – Anstrich Innen', 'Decke streichen 2x Anstrich', 'm²', 11.00::numeric),
  ('Maler – Anstrich Innen', 'Wand streichen 1x Anstrich', 'm²', 6.00::numeric),
  ('Maler – Anstrich Innen', 'Wand streichen 2x Anstrich', 'm²', 9.50::numeric),
  ('Maler – Anstrich Innen', 'Wand streichen 3x Anstrich (Vollton / Dunkelfarbe)', 'm²', 13.00::numeric),
  ('Maler – Anstrich Innen', 'Tür streichen / lackieren (einseitig)', 'Stück', 45.00::numeric),
  ('Maler – Anstrich Innen', 'Tür streichen / lackieren (beidseitig)', 'Stück', 75.00::numeric),
  ('Maler – Anstrich Innen', 'Türzarge streichen', 'Stück', 35.00::numeric),
  ('Maler – Anstrich Innen', 'Fenster streichen innen', 'Stück', 55.00::numeric),
  ('Maler – Anstrich Innen', 'Heizkörper streichen / lackieren', 'Stück', 40.00::numeric),
  ('Maler – Anstrich Innen', 'Sockelleisten / Fußleisten streichen', 'lfdm', 3.50::numeric),
  ('Maler – Anstrich Innen', 'Treppenstufen streichen / versiegeln', 'Stück', 18.00::numeric),
  ('Maler – Anstrich Innen', 'Geländer / Handlauf streichen', 'lfdm', 12.00::numeric),
  ('Maler – Anstrich Innen', 'Sonderfarbe / RAL-Farbe (Aufpreis)', 'm²', 3.00::numeric),
  ('Maler – Anstrich Innen', 'Wand mit Latexfarbe streichen 2x', 'm²', 13.00::numeric),
  ('Maler – Anstrich Innen', 'Wand mit Silikatfarbe streichen 2x', 'm²', 14.00::numeric),
  ('Maler – Anstrich Innen', 'Feuchtraumanstrich 2x', 'm²', 13.50::numeric),
  ('Maler – Anstrich Innen', 'Anti-Schimmel-Anstrich 2x', 'm²', 15.00::numeric),
  ('Maler – Anstrich Innen', 'Tapete / Raufaser überstreichen 1x', 'm²', 7.00::numeric),
  ('Maler – Anstrich Innen', 'Tapete / Raufaser überstreichen 2x', 'm²', 11.00::numeric),
  ('Maler – Anstrich Innen', 'Farbig absetzen / Akzentfläche streichen', 'm²', 12.00::numeric),
  ('Maler – Anstrich Innen', 'Trennlinie zwischen Farbtönen herstellen', 'lfdm', 3.50::numeric),
  ('Maler – Anstrich Innen', 'Rohrleitungen lackieren', 'lfdm', 9.00::numeric),
  ('Maler – Anstrich Innen', 'Stahlzarge lackieren', 'Stück', 55.00::numeric),
  ('Maler – Anstrich Innen', 'Holzdecke / Paneele deckend streichen', 'm²', 16.00::numeric),
  ('Maler – Anstrich Innen', 'Holzdecke / Paneele lasieren', 'm²', 14.00::numeric),
  ('Maler – Anstrich Außen', 'Fassade streichen 1x Anstrich', 'm²', 9.00::numeric),
  ('Maler – Anstrich Außen', 'Fassade streichen 2x Anstrich', 'm²', 14.00::numeric),
  ('Maler – Anstrich Außen', 'Fenster streichen außen', 'Stück', 70.00::numeric),
  ('Maler – Anstrich Außen', 'Holzschutzanstrich außen (Lasur)', 'm²', 13.00::numeric),
  ('Maler – Anstrich Außen', 'Metallbauteil grundieren + lackieren außen', 'm²', 18.00::numeric),
  ('Maler – Anstrich Außen', 'Rostschutzbehandlung', 'm²', 14.00::numeric),
  ('Maler – Anstrich Außen', 'Fassade reinigen / druckwaschen', 'm²', 5.00::numeric),
  ('Maler – Anstrich Außen', 'Algen- und Pilzbefall an Fassade behandeln', 'm²', 8.00::numeric),
  ('Maler – Anstrich Außen', 'Fassadengrundierung auftragen', 'm²', 6.00::numeric),
  ('Maler – Anstrich Außen', 'Fassadenrisse schließen', 'lfdm', 9.00::numeric),
  ('Maler – Anstrich Außen', 'Fassadenputz ausbessern', 'm²', 24.00::numeric),
  ('Maler – Anstrich Außen', 'Dachkasten / Untersicht streichen', 'm²', 18.00::numeric),
  ('Maler – Anstrich Außen', 'Außentür lackieren beidseitig', 'Stück', 110.00::numeric),
  ('Maler – Anstrich Außen', 'Fensterläden lackieren', 'Stück', 75.00::numeric),
  ('Maler – Tapezieren', 'Raufaser tapezieren + überstreichen 1x', 'm²', 14.00::numeric),
  ('Maler – Tapezieren', 'Raufaser tapezieren + überstreichen 2x', 'm²', 17.00::numeric),
  ('Maler – Tapezieren', 'Vliestapete tapezieren', 'm²', 18.00::numeric),
  ('Maler – Tapezieren', 'Glasfasertapete tapezieren', 'm²', 20.00::numeric),
  ('Maler – Tapezieren', 'Strukturtapete tapezieren', 'm²', 22.00::numeric),
  ('Maler – Tapezieren', 'Fototapete / Designertapete (Aufpreis Rapport)', 'm²', 8.00::numeric),
  ('Maler – Tapezieren', 'Raufaser tapezieren ohne Anstrich', 'm²', 10.00::numeric),
  ('Maler – Tapezieren', 'Papiertapete tapezieren', 'm²', 16.00::numeric),
  ('Maler – Tapezieren', 'Vinyltapete tapezieren', 'm²', 21.00::numeric),
  ('Maler – Tapezieren', 'Textiltapete tapezieren', 'm²', 28.00::numeric),
  ('Maler – Tapezieren', 'Naturwerkstofftapete / Grastapete tapezieren', 'm²', 30.00::numeric),
  ('Maler – Tapezieren', 'Metalltapete tapezieren', 'm²', 34.00::numeric),
  ('Maler – Tapezieren', 'Fototapete / Digitaldrucktapete tapezieren', 'm²', 26.00::numeric),
  ('Maler – Tapezieren', 'Mustertapete mit Rapport tapezieren', 'm²', 23.00::numeric),
  ('Maler – Tapezieren', 'Renoviervlies / Malervlies tapezieren', 'm²', 15.00::numeric),
  ('Maler – Tapezieren', 'Decke tapezieren (Aufpreis)', 'm²', 7.00::numeric),
  ('Maler – Tapezieren', 'Dachschräge tapezieren (Aufpreis)', 'm²', 5.00::numeric),
  ('Maler – Tapezieren', 'Bordüre kleben', 'lfdm', 7.00::numeric),
  ('Maler – Tapezieren', 'Ecken / Nischen / Laibungen tapezieren (Aufpreis)', 'lfdm', 6.00::numeric),
  ('Maler – Tapezieren', 'Tapetenstoß nacharbeiten', 'lfdm', 4.00::numeric),
  ('Maler – Tapezieren', 'Kleinfläche / einzelne Tapetenbahn tapezieren', 'Stück', 35.00::numeric),
  ('Maler – Lackierarbeiten', 'Holzbauteil anschleifen und entstauben', 'm²', 8.00::numeric),
  ('Maler – Lackierarbeiten', 'Holzbauteil grundieren', 'm²', 9.00::numeric),
  ('Maler – Lackierarbeiten', 'Holzbauteil lackieren 2x', 'm²', 18.00::numeric),
  ('Maler – Lackierarbeiten', 'Metallbauteil entrosten', 'm²', 12.00::numeric),
  ('Maler – Lackierarbeiten', 'Metallbauteil Rostschutzgrundierung', 'm²', 10.00::numeric),
  ('Maler – Lackierarbeiten', 'Metallbauteil lackieren 2x', 'm²', 20.00::numeric),
  ('Maler – Lackierarbeiten', 'Innentürblatt lackieren einseitig', 'Stück', 55.00::numeric),
  ('Maler – Lackierarbeiten', 'Innentürblatt lackieren beidseitig', 'Stück', 90.00::numeric),
  ('Maler – Lackierarbeiten', 'Türzarge lackieren', 'Stück', 45.00::numeric),
  ('Maler – Lackierarbeiten', 'Fensterrahmen Holz lackieren innen und außen', 'Stück', 130.00::numeric),
  ('Maler – Lackierarbeiten', 'Heizkörper Rippenradiator lackieren', 'm² Heizfläche', 18.00::numeric),
  ('Maler – Lackierarbeiten', 'Treppengeländer lackieren', 'lfdm', 18.00::numeric),
  ('Maler – Bodenbeschichtung', 'Betonboden grundieren', 'm²', 6.00::numeric),
  ('Maler – Bodenbeschichtung', 'Betonboden beschichten / versiegeln 2x', 'm²', 18.00::numeric),
  ('Maler – Bodenbeschichtung', 'Bodenfarbe auftragen (Keller, Garage)', 'm²', 12.00::numeric),
  ('Maler – Gerüst & Arbeitsmittel', 'Leitergerüst stellen (intern)', 'Pauschale', 50.00::numeric),
  ('Maler – Gerüst & Arbeitsmittel', 'Gerüst mieten / Fremdleistung (Weiterberechnung)', 'Pauschale', 0.00::numeric),
  ('Maler – Gerüst & Arbeitsmittel', 'Arbeitsbühne / Hublift mieten (Decken >3,5 m)', 'Tag', 180.00::numeric),
  ('Maler – Gerüst & Arbeitsmittel', 'Treppengerüst stellen', 'Pauschale', 120.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Zuschlag hohe Räume (>2,80 m bis 4 m)', 'm²', 2.50::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Zuschlag hohe Räume (>4 m)', 'm²', 5.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Zuschlag bewohnte Wohnung (eingeschränkt)', 'Pauschale', 80.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Zuschlag stark verschmutzter Untergrund', 'm²', 3.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Zuschlag enge Räume / Treppenhäuser', 'Pauschale', 60.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Zuschlag Wochenend- / Feiertagsarbeit (25%)', 'Pauschale', 25.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Bleihaltiger Altanstrich (Sicherheitsaufpreis)', 'Pauschale', 150.00::numeric),
  ('Maler – Reinigung & Entsorgung', 'Baustelle kehren / saugen nach Arbeit', 'Pauschale', 40.00::numeric),
  ('Maler – Reinigung & Entsorgung', 'Abdeckfolie / Abklebeband entfernen', 'Pauschale', 25.00::numeric),
  ('Maler – Reinigung & Entsorgung', 'Möbel zurückrücken', 'Stunde', 55.00::numeric),
  ('Maler – Reinigung & Entsorgung', 'Farbeimer / Verpackungen entsorgen', 'Pauschale', 20.00::numeric),
  ('Maler – Reinigung & Entsorgung', 'Sonderentsorgung lösungsmittelhaltiger Abfälle', 'Pauschale', 60.00::numeric),
  ('Maler – Reinigung & Entsorgung', 'Endreinigung Fenster / Böden', 'Stunde', 45.00::numeric),
  ('Maler – Stundenleistungen', 'Regiearbeit Geselle', 'Stunde', 65.00::numeric),
  ('Maler – Stundenleistungen', 'Regiearbeit Meister', 'Stunde', 80.00::numeric),
  ('Maler – Stundenleistungen', 'Kleinstmengenarbeit pauschal', 'Pauschale', 95.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Erschwerniszuschlag Höhe (Leitern/Gerüst über 4 m)', '%', 15.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Erschwerniszuschlag bewohnter Bereich (Schutzmaßnahmen)', '%', 10.00::numeric),
  ('Maler – Erschwernisse & Zuschläge', 'Erschwerniszuschlag Kleinflächenarbeit (unter 10 m²)', '%', 20.00::numeric),
  ('Maler – Vorbereitung & Schutz', 'Sockelleisten abkleben', 'lfdm', 0.80::numeric),
  ('Maler – Vorbereitung & Schutz', 'Holzvertäfelung / Wandbelag abkleben', 'm²', 3.00::numeric),
  ('Maler – Anstrich Innen', 'Kniestockwände streichen', 'm²', 11.00::numeric),
  ('Maler – Anstrich Innen', 'Dachschrägen streichen', 'm²', 11.00::numeric),
  ('Maler – Anstrich Innen', 'Deckenspiegel streichen', 'm²', 11.00::numeric),
  ('Maler – Tapezieren', 'Akzentwand Vliestapete', 'm²', 14.00::numeric),
  ('Maler – Anstrich Innen', 'Restwände streichen', 'm²', 9.50::numeric),
  ('Maler – Schimmel & Sanierung', 'Schimmelbehandlung / Grundierung', 'm²', 12.00::numeric),
  ('Maler – Dekorative Techniken', 'Kalkputz aufbringen', 'm²', 35.00::numeric),
  ('Maler – Spezialbeschichtungen', 'Silikatfarbe auftragen (2×)', 'm²', 13.00::numeric),
  ('Maler – Spezialbeschichtungen', 'Nikotinsperre auftragen', 'm²', 9.00::numeric),
  ('Maler – Baustelleneinrichtung', 'Gerüst stellen (Pauschale)', 'Pauschale', 450.00::numeric),
  ('Maler – Untergrundvorbereitung', 'Rissverschluss mit Gewebe', 'm²', 18.00::numeric),
  ('Maler – Baustelleneinrichtung', 'Bautrockner aufstellen und betreiben', 'Tage', 45.00::numeric),
  ('Maler – Schimmel & Sanierung', 'Anti-Schimmel-Anstrich', 'm²', 15.00::numeric),
  ('Maler – Anstrich Innen', 'Kalken / Weißkalkung', 'm²', 10.00::numeric),
  ('Maler – Dekorative Techniken', 'Spachteltechnik (Betonoptik)', 'm²', 45.00::numeric),
  ('Maler – Spezialbeschichtungen', 'Versiegelung / Schutzanstrich', 'm²', 14.00::numeric),
  ('Maler – Holzbeschichtung', 'Holzbalken anschleifen', 'lfdm', 8.00::numeric),
  ('Maler – Holzbeschichtung', 'Lasur auftragen (transparent)', 'lfdm', 9.00::numeric)
) as p(category, title, unit, unit_price)
where (
    'malerarbeiten' = any(coalesce(c.gewerke, '{}'::text[]))
    or exists (
      select 1 from price_items maler
      where maler.company_id = c.id
        and maler.category like 'Maler %'
    )
  )
  and not exists (
    select 1
    from price_items existing
    where existing.company_id = c.id
      and lower(existing.title) = lower(p.title)
      and lower(existing.unit) = lower(p.unit)
  );
